# Generated by Django 5.0 on 2023-12-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('NOMBRE', models.CharField(max_length=50)),
                ('CATEGORIA', models.CharField(max_length=50)),
                ('CLIENTE', models.CharField(max_length=50)),
                ('FECHA', models.DateTimeField()),
                ('URL', models.CharField(max_length=50)),
                ('DESCRIPCION', models.CharField(max_length=500)),
            ],
        ),
    ]
