# Generated by Django 5.0 on 2023-12-05 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('FECHA_CREACION', models.DateTimeField(auto_now_add=True)),
                ('FECHA_ACTUALIZACION', models.DateTimeField(auto_now=True)),
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('USUARIO', models.CharField(max_length=50)),
                ('CLAVE', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('FECHA_CREACION', models.DateTimeField(auto_now_add=True)),
                ('FECHA_ACTUALIZACION', models.DateTimeField(auto_now=True)),
                ('ID_USUARIO', models.OneToOneField(db_column='ID_USUARIO', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Web.usuario')),
                ('NOMBRE', models.CharField(max_length=50)),
                ('APELLIDO', models.CharField(max_length=50)),
                ('EMAIL', models.CharField(max_length=50)),
                ('FECHA_NACIMIENTO', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
